city = ['derbent', 'mahachkala', 'moscow', 'london', 'douch', 'amsterdam']
print(city)
city.insert(0, 'paris')
print(city)
city.append('madrid')
print(city)
del city[0]
print(city)
city.pop()
print(city)
city.remove('moscow')
print(city)
city.pop(1)
print(city)
print(city[3])

print(sorted(city))
print(sorted(city, reverse=True))
city.reverse()
print(city)
city.reverse()
print(city)
city.sort()
print(city)
city.sort(reverse=True)
print(city)
print(len(city))